version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rnd-app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ec2-user
AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ec2-user
ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ec2-user


