version: 0.0
os: linux

files:
  - source: /index.html
    destination: /home/ec2-user/rnd-app

hooks:


  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
      -location: scripts/validate.sh
      timeout: 300
      runas: ec2-user

  
